<?php

/**
 * Split Carousel Block
 * 
 * @package Bootstrap_Theme
 */

if (!defined('ABSPATH')) {
    exit;
}

function bootstrap_theme_render_bs_split_carousel_block($attributes, $content, $block)
{
    $carouselId = $attributes['carouselId'] ?? 'split-carousel-' . uniqid();
    $interval = $attributes['interval'] ?? '5000';
    $className = $attributes['className'] ?? '';

    $classes = array('carousel', 'slide', 'carousel-fade', 'bs-split-carousel');
    if ($className) {
        $classes[] = $className;
    }
    $class_string = implode(' ', array_unique($classes));

    ob_start();
?>
    <div class="<?php echo esc_attr($class_string); ?>" id="<?php echo esc_attr($carouselId); ?>" data-bs-ride="carousel" data-bs-interval="<?php echo esc_attr($interval); ?>">
        <!-- The indicators will be generated by JS dynamically or we can just rely on BS markup in the items. Wait, indicators need to be at the bottom of the left column. Since they are global to the carousel, we will place them here, and use CSS to position them over the left column. -->
        
        <?php 
        // We need to count the number of slides to generate indicators
        // A simple way is to parse the inner blocks count if possible, but $block object has inner_blocks
        $num_slides = isset($block->inner_blocks) ? count($block->inner_blocks) : 0;
        if ($num_slides > 1) : 
        ?>
            <div class="carousel-indicators split-carousel-indicators">
                <?php for ($i = 0; $i < $num_slides; $i++) : ?>
                    <button type="button" data-bs-target="#<?php echo esc_attr($carouselId); ?>" data-bs-slide-to="<?php echo $i; ?>" <?php echo $i === 0 ? 'class="active" aria-current="true"' : ''; ?> aria-label="Slide <?php echo $i + 1; ?>"></button>
                <?php endfor; ?>
            </div>
        <?php endif; ?>

        <div class="carousel-inner h-100">
            <?php echo $content; ?>
        </div>
    </div>
<?php
    return ob_get_clean();
}

function bootstrap_theme_register_bs_split_carousel_block()
{
    register_block_type('bootstrap-theme/bs-split-carousel', array(
        'api_version' => 3,
        'render_callback' => 'bootstrap_theme_render_bs_split_carousel_block',
        'attributes' => array(
            'carouselId' => array(
                'type' => 'string',
                'default' => ''
            ),
            'interval' => array(
                'type' => 'string',
                'default' => '5000'
            ),
            'className' => array(
                'type' => 'string',
                'default' => ''
            )
        )
    ));
}
add_action('init', 'bootstrap_theme_register_bs_split_carousel_block');
